# Exemplo de ExternalSecret usando AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret
  namespace: default
spec:
  # Intervalo de sincronização (padrão: 1h)
  refreshInterval: 1h
  
  # ClusterSecretStore a usar
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  
  # Secret do Kubernetes a ser criado
  target:
    name: example-secret
    creationPolicy: Owner
  
  # Dados a sincronizar
  data:
    # Sincronizar um secret completo
    - secretKey: database-password
      remoteRef:
        key: prod/database/credentials
        property: password
    
    - secretKey: database-username
      remoteRef:
        key: prod/database/credentials
        property: username

---
# Exemplo de ExternalSecret usando AWS SSM Parameter Store
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-ssm-secret
  namespace: default
spec:
  refreshInterval: 15m
  
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  
  target:
    name: example-ssm-secret
    creationPolicy: Owner
  
  data:
    - secretKey: api-key
      remoteRef:
        key: /prod/app/api-key

---
# Exemplo de ExternalSecret sincronizando todos os valores de um secret
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-full-secret
  namespace: default
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  
  target:
    name: example-full-secret
    creationPolicy: Owner
  
  # Sincronizar todas as propriedades do secret
  dataFrom:
    - extract:
        key: prod/app/config

---
# Exemplo de ExternalSecret com template customizado
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-templated-secret
  namespace: default
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  
  target:
    name: example-templated-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Criar connection string a partir de múltiplos secrets
        connection-string: |
          postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}
  
  data:
    - secretKey: username
      remoteRef:
        key: prod/database/credentials
        property: username
    
    - secretKey: password
      remoteRef:
        key: prod/database/credentials
        property: password
    
    - secretKey: host
      remoteRef:
        key: prod/database/config
        property: host
    
    - secretKey: port
      remoteRef:
        key: prod/database/config
        property: port
    
    - secretKey: database
      remoteRef:
        key: prod/database/config
        property: database
